name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Build
        run: pnpm build

      - uses: ryohidaka/wxt-submit@v1
        with:
          dry-run: true

          # For Chrome Extension
          chrome: true
          chrome-extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          chrome-client-id: ${{ secrets.CHROME_CLIENT_ID }}
          chrome-client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          chrome-refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

          # For Firefox Addon
          firefox: true
          firefox-extension-id: ${{ secrets.FIREFOX_EXTENSION_ID }}
          firefox-jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          firefox-jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

          # For Edge Extension
          edge: true
          edge-product-id: ${{ secrets.EDGE_PRODUCT_ID }}
          edge-client-id: ${{ secrets.EDGE_CLIENT_ID }}
          edge-client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          edge-access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
